### ISSUE TITLE
Feature Request: dump existing install into Brewfile

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew-brewdler#31]
Since this becomes homebrew official method to bundle homebrew install. I hope we can add more feature to it. Shall we?

So instead of reading Brewfile and install them, I hope to do the reverse that is writing current installation to a Brewfile. I have wrote some [similar tool](https://github.com/xu-cheng/homebrew-mine/blob/master/cmd/brew-bundle.rb) before. And if it's OK, I can work on a PR.

**Comment by mikemcquaid** [comment]
> So instead of reading Brewfile and install them, I hope to do the reverse that is writing current installation to a Brewfile. I have wrote some similar tool before. And if it's OK, I can work on a PR.

Sounds good!

**Comment by xu-cheng** [comment]
Currently, the tool is available both on homebrew tap cmd and gem. I wonder can we drop the gem support? Because it can help to do:

* Load homebrew core library much easier.
* Make it complete dependency free.
* Parse the ARGV easier. Otherwise I have do same thing twice: one for gem and one for tap cmd.

**Comment by mikemcquaid** [comment]
I'm :+1: on that if @andrew is.

**Comment by andrew** [comment]
Both of those sound good, I'll push one one last release that prints out a deprecation warning when using the gem and then we can remove the rubygem specific parts.
