### ISSUE TITLE
Feature Request: improve security

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew-brewdler#32]
Brewfile is much like a Gemfile. However, the brewdler  implementation is a lot of simpler. Currently, we use the evil `eval` to parse Brewfile and string concatenation to generate system command. So there will be a lot of security vulnerabilities. Hence, the question is can we improve it like what gem did?

I'm not a security expert. But I think we can do better.

**Comment by andrew** [comment]
Yeah definitely, this is a big issue :+1:

**Comment by mikemcquaid** [comment]
:+1:

**Comment by jamesaanderson** [comment]
It looks as if Bundler uses eval as well: https://github.com/bundler/bundler/blob/master/lib/bundler/dsl.rb#L32. I may be skipping over something though

**Comment by mikemcquaid** [comment]
I don't think `eval` is inherently bad but `instance_eval` is at least a little nicer/more secure.

**Comment by andrew** [comment]
@xu-cheng are there any more changes you'd like to make regarding this issue or can I close it?

**Comment by xu-cheng** [comment]
Yeah, we can close it.
