### ISSUE TITLE
Add verbose option

### ISSUE THREAD

**Issue by mokagio** [Homebrew/homebrew-brewdler#42]
Hi all. I love this project!

I'm using brewdle **right now** to setup a new machine. And its seems to be going smoothly, but... The output is blank! The only thing I got for this Brewfile:

```ruby
# Packages
brew 'zsh'
brew 'git'
brew 'rbenv'
brew 'ruby-build'
brew 'vim', args: ['override-system-vi']
brew 'node'
brew 'python'
brew 'brew-cask'
brew 'imagemagick'

# Apps
tap 'caskroom/cask'

cask 'iterm2'
cask 'google-chrome'
cask 'alfred'
# more stuff...
```

was 

```
$ brew brewdle
Error: No available formula for brew-cask 
Cloning into '/usr/local/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 124686, done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 124686 (delta 33), reused 2 (delta 0)
Receiving objects: 100% (124686/124686), 34.34 MiB | 1.29 MiB/s, done.
Resolving deltas: 100% (82534/82534), done.
Checking connectivity... done.
Error: Unknown command: cask
Error: Unknown command: cask
Error: Unknown command: cask
...
```

I was expecting some output like `successfully installed 'zsh'`. I think either adding redirecting brew's stdout by default, or at lest adding a verbose option, would be a nice improvement.

**Comment by mokagio** [comment]
I'm happy to have a look at doing it if this is something you guys feel makes sense. Cheers :beers:

**Comment by xu-cheng** [comment]
This is on my to-do list. But I have to wait #39 and #40 merged first.

**Comment by andrew** [comment]
@xu-cheng both #39 and #40 have been merged now :tada:

**Comment by mokagio** [comment]
@xu-cheng @andrew Sweet!

**Comment by valencik** [comment]
:+1: 
After using this to install +40 formulae, a verbose option would be lovely to see what is going on.

**Comment by jonathanwiesel** [comment]
:+1:
