### ISSUE TITLE
Reenable Coverall Notifications using Github API

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew-brewdler#46]
Previously, the coverall notifications are disabled since comments are way too annoying. Coverall recently added the support of notifications through Github build status API. More details are [here](https://github.com/lemurheavy/coveralls-public/issues/25#issuecomment-72534212).

Ping @andrew

**Comment by jamesaanderson** [comment]
Not a fan of if coverage decreases it shows as a failure but this is much less annoying than the comments. :+1:

**Comment by andrew** [comment]
Enabled that now :+1:
